export const productList = {
  feature: [
    {
      //   productImage: `${basePath}/21-330x358.jpg`,
      price: "₹800",
      productName: "Hallmark Stuffed Snoopy",
      previousPrice: "",
      ratings: 3,
    },
    {
      //   productImage: `${basePath}/9-330x358.jpg`,
      price: "₹780",
      productName: "Throated Humingbird Statue Figurine",
      previousPrice: "₹850",
      ratings: 4.5,
    },
    {
      //   productImage: `${basePath}/22-330x358.jpg`,
      price: "₹650",
      productName: "The Golden Girls Perpetual Calender",
      previousPrice: "₹720",
      ratings: 3.5,
    },
    {
      //   productImage: `${basePath}/5-330x358.jpg`,
      price: "₹810",
      productName: "The Bum Box",
      previousPrice: "₹910",
      ratings: 4,
    },
    {
      //   productImage: `${basePath}/23-330x358.jpg`,
      price: "₹500",
      productName: "Soleil Strectchy Ball Bead Mask Necklace",
      previousPrice: "₹730",
      ratings: 5,
    },
    {
      //   productImage: `${basePath}/10-330x358.jpg`,
      price: "₹550",
      productName: "Snoopy With Hearts Garland",
      previousPrice: "₹700",
      ratings: 4.5,
    },
    {
      //   productImage: `${basePath}/2-330x358.jpg`,
      price: "₹850",
      productName: "Rectangular aluminium tray",
      previousPrice: "₹840",
      ratings: 5,
    },
    {
      //   productImage: `${basePath}/18-330x358.jpg`,
      price: "₹770",
      productName: "NICI Toucan Bag Pendant Faux",
      previousPrice: "₹910",
      ratings: 4,
    },
  ],
  popular: [
    {
      //   productImage: `${basePath}/9-330x358.jpg`,
      price: "₹780",
      productName: "Throated Humingbird Statue Figurine",
      previousPrice: "₹850",
      ratings: 4.5,
    },
    {
      //   productImage: `${basePath}/22-330x358.jpg`,
      price: "₹650",
      productName: "The Golden Girls Perpetual Calender",
      previousPrice: "₹720",
      ratings: 3.5,
    },

    {
      //   productImage: `${basePath}/23-330x358.jpg`,
      price: "₹500",
      productName: "Soleil Strectchy Ball Bead Mask Necklace",
      previousPrice: "₹730",
      ratings: 5,
    },
    {
      //   productImage: `${basePath}/10-330x358.jpg`,
      price: "₹550",
      productName: "Snoopy With Hearts Garland",
      previousPrice: "₹700",
      ratings: 4.5,
    },
    {
      //   productImage: `${basePath}/2-330x358.jpg`,
      price: "₹850",
      productName: "Rectangular aluminium tray",
      previousPrice: "₹840",
      ratings: 5,
    },
    {
      //   productImage: `${basePath}/18-330x358.jpg`,
      price: "₹770",
      productName: "NICI Toucan Bag Pendant Faux",
      previousPrice: "₹910",
      ratings: 4,
    },
  ],
  onsale: [
    {
      //   productImage: `${basePath}/21-330x358.jpg`,
      price: "₹800",
      productName: "Hallmark Stuffed Snoopy",
      previousPrice: "",
      ratings: 3,
    },
    {
      //   productImage: `${basePath}/9-330x358.jpg`,
      price: "₹780",
      productName: "Throated Humingbird Statue Figurine",
      previousPrice: "₹850",
      ratings: 4.5,
    },
    {
      //   productImage: `${basePath}/22-330x358.jpg`,
      price: "₹650",
      productName: "The Golden Girls Perpetual Calender",
      previousPrice: "₹720",
      ratings: 3.5,
    },
    {
      //   productImage: `${basePath}/5-330x358.jpg`,
      price: "₹810",
      productName: "The Bum Box",
      previousPrice: "₹910",
      ratings: 4,
    },
  ],
};
